// ============================================================
// BuildAI Studio — PDF Floor Plan Generator
// Generates professional A4 PDF with floor plan and metadata
// ============================================================

import jsPDF from 'jspdf';
import type { Project } from '@/types/project';
import { distance2D, polygonCenter, formatMeasurement } from '@/lib/utils';

export function generatePDF(project: Project, canvas3dSnapshots?: string[]): void {
  const pdf = new jsPDF('l', 'mm', 'a4'); // landscape
  const pageW = pdf.internal.pageSize.getWidth();
  const pageH = pdf.internal.pageSize.getHeight();
  const margin = 15;

  const hasSnapshots = canvas3dSnapshots && canvas3dSnapshots.length > 0;
  const totalPages = hasSnapshots ? 3 : 2;

  // ─── Title Page ───
  pdf.setFillColor(9, 9, 11);
  pdf.rect(0, 0, pageW, pageH, 'F');

  pdf.setTextColor(250, 250, 250);
  pdf.setFontSize(32);
  pdf.text('BuildAI Studio', margin, 40);

  pdf.setFontSize(14);
  pdf.setTextColor(161, 161, 170);
  pdf.text('Floor Plan Report', margin, 52);

  pdf.setFontSize(20);
  pdf.setTextColor(250, 250, 250);
  pdf.text(project.name, margin, 80);

  pdf.setFontSize(11);
  pdf.setTextColor(161, 161, 170);
  if (project.description) {
    pdf.text(project.description, margin, 92);
  }

  pdf.setFontSize(10);
  pdf.text(`Project ID: ${project.id.substring(0, 8)}`, margin, 115);
  pdf.text(`Date: ${new Date().toLocaleDateString()}`, margin, 123);
  pdf.text(`Rooms: ${project.rooms.length}`, margin, 131);
  pdf.text(`Furniture: ${project.furniture.length}`, margin, 139);
  pdf.text(`Unit: ${project.unit}`, margin, 147);

  // Footer
  pdf.setFontSize(8);
  pdf.setTextColor(82, 82, 91);
  pdf.text('Generated by BuildAI Studio — For planning purposes only. Not for construction.', margin, pageH - 10);
  pdf.setFontSize(7);
  pdf.setTextColor(160, 160, 160);
  pdf.text(`Page 1 of ${totalPages}`, pageW - margin - 20, pageH - 10);

  // ─── Floor Plan Page ───
  pdf.addPage('a4', 'l');
  pdf.setFillColor(255, 255, 255);
  pdf.rect(0, 0, pageW, pageH, 'F');

  // Header
  pdf.setTextColor(9, 9, 11);
  pdf.setFontSize(14);
  pdf.text(`${project.name} — Floor Plan`, margin, 12);

  pdf.setFontSize(8);
  pdf.setTextColor(113, 113, 122);
  pdf.text(`Scale: 1:100 | Grid: ${project.gridSize}m | ${new Date().toLocaleDateString()}`, margin, 19);

  // Calculate bounds
  const allPoints: { x: number; y: number }[] = [];
  project.walls.forEach((w) => {
    allPoints.push(w.start, w.end);
  });
  project.rooms.forEach((r) => {
    allPoints.push(...r.corners);
  });

  if (allPoints.length === 0) {
    pdf.setFontSize(12);
    pdf.setTextColor(161, 161, 170);
    pdf.text('No floor plan data to display.', pageW / 2 - 30, pageH / 2);
    pdf.save(`${project.name.replace(/\s+/g, '_')}_floorplan.pdf`);
    return;
  }

  const minX = Math.min(...allPoints.map((p) => p.x));
  const minY = Math.min(...allPoints.map((p) => p.y));
  const maxX = Math.max(...allPoints.map((p) => p.x));
  const maxY = Math.max(...allPoints.map((p) => p.y));
  const boundsW = maxX - minX || 1;
  const boundsH = maxY - minY || 1;

  // Drawing area
  const drawX = margin;
  const drawY = 25;
  const drawW = pageW - margin * 2;
  const drawH = pageH - drawY - margin - 10;

  const scaleVal = Math.min(drawW / boundsW, drawH / boundsH) * 0.85;
  const offsetX = drawX + (drawW - boundsW * scaleVal) / 2;
  const offsetY = drawY + (drawH - boundsH * scaleVal) / 2;

  const toPageX = (x: number) => offsetX + (x - minX) * scaleVal;
  const toPageY = (y: number) => offsetY + (y - minY) * scaleVal;

  // Draw grid
  pdf.setDrawColor(230, 230, 230);
  pdf.setLineWidth(0.1);
  for (let gx = Math.floor(minX); gx <= Math.ceil(maxX); gx += project.gridSize * 2) {
    pdf.line(toPageX(gx), toPageY(minY), toPageX(gx), toPageY(maxY));
  }
  for (let gy = Math.floor(minY); gy <= Math.ceil(maxY); gy += project.gridSize * 2) {
    pdf.line(toPageX(minX), toPageY(gy), toPageX(maxX), toPageY(gy));
  }

  // Draw rooms (filled)
  project.rooms.forEach((room) => {
    if (room.corners.length < 3) return;
    const points = room.corners.map((c) => [toPageX(c.x), toPageY(c.y)] as [number, number]);

    pdf.setFillColor(245, 245, 244);
    pdf.setDrawColor(200, 200, 200);
    pdf.setLineWidth(0.2);

    pdf.moveTo(points[0][0], points[0][1]);
    for (let i = 1; i < points.length; i++) {
      pdf.lineTo(points[i][0], points[i][1]);
    }
    pdf.lineTo(points[0][0], points[0][1]);
    pdf.fill();

    // Room label
    const center = polygonCenter(room.corners);
    pdf.setFontSize(9);
    pdf.setTextColor(60, 60, 60);
    const labelWidth = pdf.getTextWidth(room.label);
    pdf.text(room.label, toPageX(center.x) - labelWidth / 2, toPageY(center.y));

    // Room area
    if (room.area) {
      const areaText = `${room.area.toFixed(1)} m²`;
      const areaWidth = pdf.getTextWidth(areaText);
      pdf.setFontSize(7);
      pdf.setTextColor(130, 130, 130);
      pdf.text(areaText, toPageX(center.x) - areaWidth / 2, toPageY(center.y) + 4);
    }
  });

  // Draw walls
  pdf.setDrawColor(30, 30, 30);
  pdf.setLineWidth(0.8);
  project.walls.forEach((wall) => {
    pdf.line(
      toPageX(wall.start.x), toPageY(wall.start.y),
      toPageX(wall.end.x), toPageY(wall.end.y)
    );

    const length = distance2D(wall.start, wall.end);
    const midX = (wall.start.x + wall.end.x) / 2;
    const midY = (wall.start.y + wall.end.y) / 2;
    const dimText = formatMeasurement(length, project.unit);
    pdf.setFontSize(6);
    pdf.setTextColor(100, 100, 240);
    pdf.text(dimText, toPageX(midX) + 2, toPageY(midY) - 2);
  });

  // Draw doors
  pdf.setDrawColor(239, 68, 68);
  pdf.setLineWidth(0.4);
  project.doors.forEach((door) => {
    const wall = project.walls.find((w) => w.id === door.wallId);
    if (!wall) return;
    const wallLen = distance2D(wall.start, wall.end);
    if (wallLen === 0) return;
    const t = door.offsetAlongWall / wallLen;
    const dx = wall.end.x - wall.start.x;
    const dy = wall.end.y - wall.start.y;
    const px = wall.start.x + dx * t;
    const py = wall.start.y + dy * t;

    // Door gap
    pdf.setDrawColor(255, 255, 255);
    pdf.setLineWidth(1.2);
    const doorEndT = Math.min(1, (door.offsetAlongWall + door.width) / wallLen);
    const endX = wall.start.x + dx * doorEndT;
    const endY = wall.start.y + dy * doorEndT;
    pdf.line(toPageX(px), toPageY(py), toPageX(endX), toPageY(endY));

    // Door label
    pdf.setFontSize(5);
    pdf.setTextColor(239, 68, 68);
    pdf.text('D', toPageX(px) - 1, toPageY(py) - 2);
  });

  // Draw windows
  project.windows.forEach((win) => {
    const wall = project.walls.find((w) => w.id === win.wallId);
    if (!wall) return;
    const wallLen = distance2D(wall.start, wall.end);
    if (wallLen === 0) return;
    const t = win.offsetAlongWall / wallLen;
    const dx = wall.end.x - wall.start.x;
    const dy = wall.end.y - wall.start.y;
    const px = wall.start.x + dx * t;
    const py = wall.start.y + dy * t;

    pdf.setDrawColor(6, 182, 212);
    pdf.setLineWidth(0.6);
    const winEndT = Math.min(1, (win.offsetAlongWall + win.width) / wallLen);
    const endX = wall.start.x + dx * winEndT;
    const endY = wall.start.y + dy * winEndT;
    pdf.line(toPageX(px), toPageY(py), toPageX(endX), toPageY(endY));

    pdf.setFontSize(5);
    pdf.setTextColor(6, 182, 212);
    pdf.text('W', toPageX(px) - 1, toPageY(py) - 2);
  });

  // Draw furniture
  pdf.setLineWidth(0.3);
  project.furniture.forEach((item) => {
    const x = toPageX(item.transform.position.x - item.width / 2);
    const y = toPageY(item.transform.position.z - item.depth / 2);
    const w = item.width * scaleVal;
    const h = item.depth * scaleVal;

    pdf.setDrawColor(120, 120, 120);
    pdf.setFillColor(240, 240, 240);
    pdf.rect(x, y, w, h, 'FD');

    pdf.setFontSize(4.5);
    pdf.setTextColor(80, 80, 80);
    const nameW = pdf.getTextWidth(item.name);
    if (nameW < w - 1) {
      pdf.text(item.name, x + (w - nameW) / 2, y + h / 2 + 1);
    }
  });

  // North arrow
  pdf.setFontSize(10);
  pdf.setTextColor(30, 30, 30);
  pdf.text('↑ N', pageW - margin - 10, drawY + 8);

  // Scale bar
  const scaleBarLen = 1 * scaleVal;
  const sbX = pageW - margin - scaleBarLen - 5;
  const sbY = pageH - margin - 5;
  pdf.setDrawColor(30, 30, 30);
  pdf.setLineWidth(0.5);
  pdf.line(sbX, sbY, sbX + scaleBarLen, sbY);
  pdf.line(sbX, sbY - 2, sbX, sbY + 2);
  pdf.line(sbX + scaleBarLen, sbY - 2, sbX + scaleBarLen, sbY + 2);
  pdf.setFontSize(6);
  pdf.text('1m', sbX + scaleBarLen / 2 - 3, sbY - 3);

  // Footer
  pdf.setFontSize(7);
  pdf.setTextColor(160, 160, 160);
  pdf.text('BuildAI Studio — For planning purposes only', margin, pageH - 5);
  pdf.text(`Page 2 of ${totalPages}`, pageW - margin - 20, pageH - 5);

  // ─── 3D Perspective Renders Page (2×2 Grid) ───
  if (hasSnapshots) {
    pdf.addPage('a4', 'l');
    pdf.setFillColor(9, 9, 11);
    pdf.rect(0, 0, pageW, pageH, 'F');

    // Header
    pdf.setTextColor(250, 250, 250);
    pdf.setFontSize(14);
    pdf.text(`${project.name} — 3D Perspective Renders`, margin, 14);

    pdf.setFontSize(8);
    pdf.setTextColor(161, 161, 170);
    pdf.text(`Generated on ${new Date().toLocaleDateString()}`, margin, 21);

    // 2×2 grid layout
    const labels = ['Perspective View', 'Front View', 'Side View', "Bird's Eye View"];
    const gridGap = 6;
    const gridStartY = 26;
    const gridAvailW = pageW - margin * 2 - gridGap;
    const gridAvailH = pageH - gridStartY - margin - 10 - gridGap;
    const cellW = gridAvailW / 2;
    const cellH = gridAvailH / 2;

    for (let i = 0; i < Math.min(canvas3dSnapshots!.length, 4); i++) {
      const col = i % 2;
      const row = Math.floor(i / 2);
      const cx = margin + col * (cellW + gridGap);
      const cy = gridStartY + row * (cellH + gridGap);

      // Image
      try {
        pdf.addImage(canvas3dSnapshots![i], 'JPEG', cx, cy, cellW, cellH - 5);
      } catch (e) {
        pdf.setFillColor(30, 30, 30);
        pdf.rect(cx, cy, cellW, cellH - 5, 'F');
        pdf.setTextColor(100, 100, 100);
        pdf.setFontSize(8);
        pdf.text('Capture failed', cx + cellW / 2 - 12, cy + (cellH - 5) / 2);
      }

      // Border
      pdf.setDrawColor(60, 60, 60);
      pdf.setLineWidth(0.3);
      pdf.rect(cx, cy, cellW, cellH - 5, 'S');

      // Label below image
      pdf.setFontSize(7);
      pdf.setTextColor(200, 200, 200);
      const label = labels[i] || `View ${i + 1}`;
      const labelW = pdf.getTextWidth(label);
      pdf.text(label, cx + (cellW - labelW) / 2, cy + cellH - 2);
    }

    // Footer
    pdf.setFontSize(7);
    pdf.setTextColor(100, 100, 100);
    pdf.text('BuildAI Studio — For planning purposes only', margin, pageH - 5);
    pdf.text(`Page 3 of ${totalPages}`, pageW - margin - 20, pageH - 5);
  }

  // Save
  pdf.save(`${project.name.replace(/\s+/g, '_')}_floorplan.pdf`);
}
